ivo://ivoa.net/std/GMS#search-1.0=ivo://skao.int/gms
ivo://ivoa.net/std/GMS#users-1.0=ivo://skao.int/gms
ivo://ivoa.net/std/UMS#users-0.1=ivo://skao.int/gms
ivo://ivoa.net/std/UMS#users-1.0=ivo://skao.int/gms
ivo://ivoa.net/sso#OAuth=https://ska-iam.stfc.ac.uk/
ivo://ivoa.net/sso#OpenID=https://ska-iam.stfc.ac.uk/

ca.nrc.cadc.reg.client.RegistryClient.baseURL=https://reg.swesrc.chalmers.se
