ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
ca.nrc.cadc.util.Log4jInit.messageOnly=true
ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager

# database connection pools
org.opencadc.posix.mapper.maxActive=4
org.opencadc.posix.mapper.url=jdbc:postgresql://postgres-pm:5432/posix_mapper_dev
org.opencadc.posix.mapper.username=postgres
org.opencadc.posix.mapper.password=postgres
