CREATE TABLE <schema>.Users
(
    issuer   VARCHAR(255) NOT NULL,
    subject  VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE,
    uid      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_users PRIMARY KEY (issuer, subject)
);

CREATE TABLE <schema>.Groups
(
    groupURI  VARCHAR(255),
    gid       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_groups PRIMARY KEY (groupURI)
);
